# Generated by Django 4.0.4 on 2022-05-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_address_user_alter_userprofile_address'),
        ('products', '0008_orderproduct_customer_orderproduct_ordered'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'vendor')},
        ),
    ]
