# Generated by Django 4.0.4 on 2022-05-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_create_product_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-modified']},
        ),
    ]
